import SectionContainer from '@/components/templates/SectionContainer';
import Header from '@/components/atoms/Header';
import MainContainer from '@/components/templates/MainContainer';
import PageContainer from '@/components/templates/PageContainer';
import Typography from '@/components/atoms/Typography';
import AccountProfile from '@/components/organisms/AccountProfile';
import CompagnyProfile from '@/components/organisms/CompanyProfile';
import UserProfile from '@/components/organisms/UserProfile/UserProfile';
import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import HeaderWedge from '@/components/templates/HeaderWedge';

const Home: NextPage = () => (
  <PageContainer>
    <Head>
      <title>Mansa Profile</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Header>
      <Image
        src="/mansa.png"
        width="150"
        height="70"
        objectFit="contain"
        alt="mansa"
      />
    </Header>
    <HeaderWedge />
    <MainContainer>
      <UserProfile />
      <SectionContainer>
        <Typography fontSize="1.5rem" fontWeight="bold">
          Company
        </Typography>
        <CompagnyProfile />
      </SectionContainer>
      <SectionContainer>
        <Typography fontSize="1.5rem" fontWeight="bold">
          Accounts
        </Typography>
        <AccountProfile />
      </SectionContainer>
    </MainContainer>
  </PageContainer>
);

export default Home;
